module top (
    input wire i_clk,
    input wire i_rst_n
);

    wire [15:0] w_instr;
    wire [15:0]  w_data_from_dmem;
    wire        w_dmem_wen;
    wire [15:0] w_addr_to_dmem;
    wire [15:0] w_data_to_dmem;
    wire [15:0] w_addr_to_imem;
    wire [15:0] w_observed_reg_data; // 観測用のレジスタデータ（R7）

    // SVA_WIRE_BEGIN (auto-generated by update_top_ports.py, do not edit manually)
    wire [15:0]      w_debug_instr;
    wire  [3:0]      w_debug_rs1_addr;
    wire [15:0]      w_debug_rs1_data;
    wire  [3:0]      w_debug_rs2_addr;
    wire [15:0]      w_debug_rs2_data;
    wire  [3:0]      w_debug_rd_addr;
    wire [15:0]      w_debug_rd_data;
    wire             w_debug_regfile_wen;
    wire             w_debug_dmem_wen;
    wire [15:0]      w_debug_adder_to_dmem;
    wire [15:0]      w_debug_data_to_dmem;
    wire [15:0]      w_debug_data_from_dmem;
    wire [15:0]      w_debug_now_pc;
    wire             w_debug_flag_n;
    wire             w_debug_flag_v;
    wire             w_debug_flag_z;
    // SVA_WIRE_END






    // 命令メモリのインスタンス化
    imem u_imem (
        .i_addr  (w_addr_to_imem),
        .clk     (i_clk          ),
        .o_instr (w_instr       )
    );

    // データメモリのインスタンス化
    dmem u_dmem (
        .i_clk  (i_clk           ),
        .i_rst_n(i_rst_n         ),
        .i_addr (w_addr_to_dmem  ),
        .i_wen  (w_dmem_wen      ),
        .i_data (w_data_to_dmem  ),
        .o_data (w_data_from_dmem)
    );

    // CPUのインスタンス化 コメントはIOのビット幅を示す
    cpu u_cpu (
        .i_clk            (i_clk           ), //[1]
        .i_rst_n          (i_rst_n         ), //[1]
        .i_instr          (w_instr         ), //[8]
        .i_data_from_dmem (w_data_from_dmem), //[8]

        .o_addr_to_dmem   (w_addr_to_dmem  ), //[8]
        .o_data_to_dmem   (w_data_to_dmem  ), //[8]
        .o_addr_to_imem   (w_addr_to_imem  ), //[8]
        .o_dmem_wen       (w_dmem_wen      ), //[1]
        .o_observed_reg_data(w_observed_reg_data), //[16]

        // CPU_DEBUG_BEGIN (auto-generated by update_top_ports.py, do not edit manually)
        .o_debug_instr          (w_debug_instr         ),   //[16]
        .o_debug_rs1_addr       (w_debug_rs1_addr      ),   //[4]
        .o_debug_rs1_data       (w_debug_rs1_data      ),   //[16]
        .o_debug_rs2_addr       (w_debug_rs2_addr      ),   //[4]
        .o_debug_rs2_data       (w_debug_rs2_data      ),   //[16]
        .o_debug_rd_addr        (w_debug_rd_addr       ),   //[4]
        .o_debug_rd_data        (w_debug_rd_data       ),   //[16]
        .o_debug_regfile_wen    (w_debug_regfile_wen   ),   //[1]
        .o_debug_dmem_wen       (w_debug_dmem_wen      ),   //[1]
        .o_debug_adder_to_dmem  (w_debug_adder_to_dmem ),   //[16]
        .o_debug_data_to_dmem   (w_debug_data_to_dmem  ),   //[16]
        .o_debug_data_from_dmem (w_debug_data_from_dmem),   //[16]
        .o_debug_now_pc         (w_debug_now_pc        ),   //[16]
        .o_debug_flag_n         (w_debug_flag_n        ),   //[1]
        .o_debug_flag_v         (w_debug_flag_v        ),   //[1]
        .o_debug_flag_z         (w_debug_flag_z        )   //[1]
        // CPU_DEBUG_END
    );

    // SVA_INST_BEGIN (auto-generated by update_top_ports.py, do not edit manually)
    sva_cpu_gen u_sva_cpu_gen (
        .i_clk                  (i_clk                 ),
        .i_rst_n                (i_rst_n               ),
        .w_debug_instr          (w_debug_instr         ),
        .w_debug_rs1_addr       (w_debug_rs1_addr      ),
        .w_debug_rs1_data       (w_debug_rs1_data      ),
        .w_debug_rs2_addr       (w_debug_rs2_addr      ),
        .w_debug_rs2_data       (w_debug_rs2_data      ),
        .w_debug_rd_addr        (w_debug_rd_addr       ),
        .w_debug_rd_data        (w_debug_rd_data       ),
        .w_debug_regfile_wen    (w_debug_regfile_wen   ),
        .w_debug_dmem_wen       (w_debug_dmem_wen      ),
        .w_debug_adder_to_dmem  (w_debug_adder_to_dmem ),
        .w_debug_data_to_dmem   (w_debug_data_to_dmem  ),
        .w_debug_data_from_dmem (w_debug_data_from_dmem),
        .w_debug_now_pc         (w_debug_now_pc        ),
        .w_debug_flag_n         (w_debug_flag_n        ),
        .w_debug_flag_v         (w_debug_flag_v        ),
        .w_debug_flag_z         (w_debug_flag_z        )
    );
    // SVA_INST_END





endmodule
